In [1]:

test_ds_path = ".\..\Datasets\store_data.csv"

with open(test_ds_path, "r") as f:

    lines = f.readlines()
    inventory = list()
    tuples = list()

    for line in lines:
        transaction = line.strip().split(",")
        #print(transaction)
        tuples.append(transaction)
        for element in transaction:
            if element.strip().replace(' ','_').replace('&','and') not in inventory:
                inventory.append(element.strip().replace(' ','_').replace('&','and'))

In [2]:
print(len(inventory))

120


In [3]:

print(inventory)
inventory.pop()
inventory.sort()
print(inventory)

['shrimp', 'almonds', 'avocado', 'vegetables_mix', 'green_grapes', 'whole_weat_flour', 'yams', 'cottage_cheese', 'energy_drink', 'tomato_juice', 'low_fat_yogurt', 'green_tea', 'honey', 'salad', 'mineral_water', 'salmon', 'antioxydant_juice', 'frozen_smoothie', 'spinach', 'olive_oil', 'burgers', 'meatballs', 'eggs', 'chutney', 'turkey', 'milk', 'energy_bar', 'whole_wheat_rice', 'whole_wheat_pasta', 'french_fries', 'soup', 'light_cream', 'shallot', 'frozen_vegetables', 'spaghetti', 'pet_food', 'cookies', 'cooking_oil', 'champagne', 'chocolate', 'chicken', 'oil', 'fresh_tuna', 'tomatoes', 'black_tea', 'extra_dark_chocolate', 'protein_bar', 'red_wine', 'pasta', 'pepper', 'shampoo', 'rice', 'sparkling_water', 'ham', 'body_spray', 'pancakes', 'grated_cheese', 'white_wine', 'toothpaste', 'parmesan_cheese', 'fresh_bread', 'ground_beef', 'escalope', 'herb_and_pepper', 'tomato_sauce', 'magazines', 'strawberries', 'strong_cheese', 'pickles', 'cake', 'hot_dogs', 'brownies', 'cereals', 'clothes_acc

In [4]:
print(len(inventory))

119


In [5]:
import pandas as pd


In [6]:
test_dataset = pd.DataFrame(
    [[1 if item in row else 0 for item in inventory] for row in tuples],
    columns=inventory
)

In [7]:
test_dataset.head(3)

almonds  antioxydant_juice  asparagus  avocado  babies_food  bacon  \
0        1                  0          0        1            0      0   
1        0                  0          0        0            0      0   
2        0                  0          0        0            0      0   

   barbecue_sauce  black_tea  blueberries  body_spray  ...  turkey  \
0               0          0            0           0  ...       0   
1               0          0            0           0  ...       0   
2               0          0            0           0  ...       0   

   vegetables_mix  water_spray  white_wine  whole_weat_flour  \
0               0            0           0                 0   
1               0            0           0                 0   
2               0            0           0                 0   

   whole_wheat_pasta  whole_wheat_rice  yams  yogurt_cake  zucchini  
0                  0                 0     1            0         0  
1                  0                 0     0            0         0  
2                  0                 0     0            0         0  

[3 rows x 119 columns]

In [8]:
test_dataset.columns

Index(['almonds', 'antioxydant_juice', 'asparagus', 'avocado', 'babies_food',
       'bacon', 'barbecue_sauce', 'black_tea', 'blueberries', 'body_spray',
       ...
       'turkey', 'vegetables_mix', 'water_spray', 'white_wine',
       'whole_weat_flour', 'whole_wheat_pasta', 'whole_wheat_rice', 'yams',
       'yogurt_cake', 'zucchini'],
      dtype='object', length=119)

In [9]:
type(test_dataset.columns)

pandas.core.indexes.base.Index

In [10]:
test_dataset['zucchini'].sum()


np.int64(71)

In [11]:
for tuple in test_dataset.itertuples():
    print(tuple)
    print(int( getattr(tuple, 'almonds')))
    print(type(tuple))
    break

Pandas(Index=0, almonds=1, antioxydant_juice=0, asparagus=0, avocado=1, babies_food=0, bacon=0, barbecue_sauce=0, black_tea=0, blueberries=0, body_spray=0, bramble=0, brownies=0, bug_spray=0, burger_sauce=0, burgers=0, butter=0, cake=0, candy_bars=0, carrots=0, cauliflower=0, cereals=0, champagne=0, chicken=0, chili=0, chocolate=0, chocolate_bread=0, chutney=0, cider=0, clothes_accessories=0, cookies=0, cooking_oil=0, corn=0, cottage_cheese=0, cream=0, dessert_wine=0, eggplant=0, eggs=0, energy_bar=0, energy_drink=0, escalope=0, extra_dark_chocolate=0, flax_seed=0, french_fries=0, french_wine=0, fresh_bread=0, fresh_tuna=0, fromage_blanc=0, frozen_smoothie=0, frozen_vegetables=0, gluten_free_bar=0, grated_cheese=0, green_beans=0, green_grapes=0, green_tea=0, ground_beef=0, gums=0, ham=0, hand_protein_bar=0, herb_and_pepper=0, honey=1, hot_dogs=0, ketchup=0, light_cream=0, light_mayo=0, low_fat_yogurt=0, magazines=0, mashed_potato=0, mayonnaise=0, meatballs=0, melons=0, milk=0, mineral_

In [12]:
import numpy as np
for tuple in test_dataset.itertuples(False):
    print(tuple)
    test_tuple = tuple
    print(type(tuple))
    print(np.asarray(tuple))
    break

dataset_mini = test_dataset.head(3)


print(dataset_mini)

Pandas(almonds=1, antioxydant_juice=0, asparagus=0, avocado=1, babies_food=0, bacon=0, barbecue_sauce=0, black_tea=0, blueberries=0, body_spray=0, bramble=0, brownies=0, bug_spray=0, burger_sauce=0, burgers=0, butter=0, cake=0, candy_bars=0, carrots=0, cauliflower=0, cereals=0, champagne=0, chicken=0, chili=0, chocolate=0, chocolate_bread=0, chutney=0, cider=0, clothes_accessories=0, cookies=0, cooking_oil=0, corn=0, cottage_cheese=0, cream=0, dessert_wine=0, eggplant=0, eggs=0, energy_bar=0, energy_drink=0, escalope=0, extra_dark_chocolate=0, flax_seed=0, french_fries=0, french_wine=0, fresh_bread=0, fresh_tuna=0, fromage_blanc=0, frozen_smoothie=0, frozen_vegetables=0, gluten_free_bar=0, grated_cheese=0, green_beans=0, green_grapes=0, green_tea=0, ground_beef=0, gums=0, ham=0, hand_protein_bar=0, herb_and_pepper=0, honey=1, hot_dogs=0, ketchup=0, light_cream=0, light_mayo=0, low_fat_yogurt=0, magazines=0, mashed_potato=0, mayonnaise=0, meatballs=0, melons=0, milk=0, mineral_water=0, 

In [13]:
dataset_mini.loc[0,'almonds']

np.int64(1)

In [14]:

from pandas import DataFrame


def support(T: DataFrame ,X_U_Y: list | dict):
    '''
    Parameters:
    T (dataframe)
    X_U_Y (list | dict) : name of the attributes considered (X U Y)
    Return:
    float: support of the attributes in the dataset
    '''
    for attribute in X_U_Y:
        if attribute not in T.columns:
             return ValueError
    count = 0
    for tuple in T.itertuples(False):
        contained = True
        for attribute in X_U_Y:
            try: 
                if getattr(tuple,attribute) == 0:
                    contained = False
                    break
            except AttributeError:
                contained = False,
                break

        if contained:
            count += 1 
    return count/len(T)
    

In [15]:
support(test_dataset,['herb_and_pepper'])

0.0

In [16]:

def confidence(T: DataFrame, X: list | dict, Y: list | dict):
    '''
    Parameters:
    T (dataframe)
    X ( list | dict): X part of X ==> Y rule
    X (list | disct): Y part of X ==> Y rule
    '''
    if len(X)+len(Y) > len(T.columns):
        return ValueError
    for item in X:
        if Y.__contains__(item):
            return ValueError # XY = empty set
    
    countX=0
    countY=0
    for tuple in T.itertuples():
        containedX = True
        for attribute in X:
            if getattr(tuple,attribute) == 0:
                containedX = False
                break
        if containedX:
            countX += 1
            containedY=True
            for attribute in Y:
                if attribute == '':
                    containedY = False
                    break
                if getattr(tuple,attribute) == 0:
                    containedY = False
                    break
            if containedY:
                countY += 1
    return countY/countX    

In [17]:
confidence(test_dataset,['spaghetti','champagne'],['cookies'])
#spaghetti,champagne,cookies

0.08

In [18]:
def Apriori(items, dataset, min_sup, levels: int):
    '''
    rules[0] = empty set
    rules[1] = rules of length 1
    rules[2] = rules of length 2


    rules[len(items)] = items
    ...
    '''
    rules = [
        [],
        [ [item] for item in items ]
    ]


    # iterate over all the possible rules length from 1 to len(items)
    for i in range(1, levels+1):
        print(f"Apriori Level: {i}")
        # remove all the rules in rules[i]
        # that don't have a support of at least min_sup

        #print(f"RULES[{i}] BEFORE", rules[i])

        rules[i] = [
            rule
            for rule in rules[i]
            if support(dataset, rule) >= min_sup
        ]
        
        '''
        print(f"RULES[{i}] SUPPORT", [
            support(dataset, rule)
            for rule in rules[i]
        ]
        )'''


        #print(f"RULES[{i}] AFTER", rules[i])

        if len(rules[i]) == 0:
            break


        # generate all the possibile 
        # rules with i+1 elements
        rules.append([]) # create the element rules[i+1]

        #print("RULE[i]", rules[i])
        #print("RULE[i+1]", rules[i+1])
        for rule in rules[i]:
            for item in items:

                # skip if item is already inside the rule
                if item in rule:
                    continue

                rules[i+1].append ( rule + [item] )
                # create a new rule composed of rule + [item]


        #print("RULE[i+1]", rules[i+1])
    
        #print()
        #print()
        #print()

    return rules

In [19]:

#rules = Apriori(inventory,test_dataset,0.004, 4)

In [20]:
#print(rules)

In [21]:
import random
random.random()

0.9627254305028914

In [22]:
support_vector = [[item,support(test_dataset,[item])] for item in inventory]
print(support_vector)
mean_support = np.mean([sublist[1] for sublist in support_vector])
print(mean_support)

frequent_item = []
infrequent_item = []


for item in support_vector:
    if item[1]>mean_support:
        frequent_item.append(item)
    else:
        infrequent_item.append(item)



support_vector
print(support_vector)
print(frequent_item)
print(infrequent_item)

print(len(support_vector))
print(len(frequent_item))
print(len(infrequent_item))

[['almonds', 0.020397280362618318], ['antioxydant_juice', 0.0], ['asparagus', 0.004666044527396347], ['avocado', 0.03332888948140248], ['babies_food', 0.0], ['bacon', 0.008665511265164644], ['barbecue_sauce', 0.0], ['black_tea', 0.0], ['blueberries', 0.009198773496867084], ['body_spray', 0.0], ['bramble', 0.0018664178109585388], ['brownies', 0.03372883615517931], ['bug_spray', 0.0], ['burger_sauce', 0.0], ['burgers', 0.0871883748833489], ['butter', 0.030129316091187842], ['cake', 0.08105585921877083], ['candy_bars', 0.0], ['carrots', 0.01533128916144514], ['cauliflower', 0.004799360085321957], ['cereals', 0.025729902679642713], ['champagne', 0.04679376083188908], ['chicken', 0.05999200106652446], ['chili', 0.0061325156645780565], ['chocolate', 0.1638448206905746], ['chocolate_bread', 0.0], ['chutney', 0.0041327822956939075], ['cider', 0.010531929076123183], ['clothes_accessories', 0.0], ['cookies', 0.08038928142914278], ['cooking_oil', 0.0], ['corn', 0.004799360085321957], ['cottage_ch

In [23]:
import random

def MASK_Distortion(dataset: DataFrame, p: float):
    '''
    MASK
    
    choose a probability p

    2 event
    P(x = true) -> 1-p % -> we add or remove an element in the transaction
    P(x = false) -> p% -> the transaction remains the same
    '''
    distorted_dataset = dataset.copy(deep=True)
    for i in range(0,len(distorted_dataset)):
        for column in distorted_dataset.columns:
            event = random.random()
            if event > p:
                distorted_dataset.loc[i, column] = int(not dataset.loc[i, column])

    return distorted_dataset

        



In [24]:
def MASK_frequent_infrequent_items(support_vector,sup_min):
    frequent_item = []
    infrequent_item = []

    for item in support_vector:
        if item[1]>sup_min:
            frequent_item.append(item[0])
        else:
            infrequent_item.append(item[0])
    return frequent_item,infrequent_item

In [25]:
p = 0.9
distorted_test_dataset = MASK_Distortion(test_dataset,p)

In [26]:
def hammingDistanceBitwise(a:int,b:int):
    return (a^b).bit_count()

In [27]:
hammingDistanceBitwise(int(1),int(2))

2

In [28]:
import numpy as np
import math
M = np.diag([math.pow(2,3) for i in range(0,3)])
print(M)

[[8. 0. 0.]
 [0. 8. 0.]
 [0. 0. 8.]]


In [29]:
import numpy as np
import math
def computeM(size: int, p: float):
    max_exp = int(math.log2(size))
    M = np.diag([math.pow(p,max_exp) for i in range(size)])
    for i in range(0,size):
        for j in range(i+1,size):
            difference = hammingDistanceBitwise(i,j)
            M[i][j] = math.pow(1-p,difference)*math.pow(p,max_exp-difference)

    for i in range(1,size):
        for j in range(i,-1,-1):
            M[i][j] = M[j][i]

    return M


In [30]:
M_test = computeM(int(math.pow(2,2)),0.1)
print(M_test)
print(sum(M_test[0]))

[[0.01 0.09 0.09 0.81]
 [0.09 0.01 0.81 0.09]
 [0.09 0.81 0.01 0.09]
 [0.81 0.09 0.09 0.01]]
1.0


In [32]:
def computeLinC_D(dataset: DataFrame,rule: list | dict):
    linC_D = np.zeros(len(rule)+1,dtype=int)
    reducted_ds = dataset[rule] # posso prendere solo le colonne interessanti
    for tuple in reducted_ds.itertuples(False):
        '''sum = 0
        for attribute in rule:
            sum += getattr(tuple,attribute) # o farlo qua con il for
            linC_D[sum] += 1
        '''
        
        linC_D[np.sum(tuple,axis=0)] += 1
    
    return linC_D
    

In [57]:
def vectormatrixProdMod(linC_D,matrix):
    size = matrix.shape[0]
    row = matrix[size-1]
    sum=0
    for j in range(len(linC_D)):
        index = int(math.pow(2,j))-1
        #print(str(row[index])+" * "+str(linC_D[j]))
        sum += row[index]*linC_D[j]
    return sum

In [35]:
from numpy.linalg import inv

M_test = inv(computeM(2**2,p))
print(M_test)
print(sum(M_test[3]))

[[ 1.265625 -0.140625 -0.140625  0.015625]
 [-0.140625  1.265625  0.015625 -0.140625]
 [-0.140625  0.015625  1.265625 -0.140625]
 [ 0.015625 -0.140625 -0.140625  1.265625]]
1.0


In [58]:
from numpy.linalg import inv

def MASK_Support(dataset:DataFrame, rule, p:float, M_inv = None):
    if M_inv is None:
        M_inv = inv(
            computeM(
                size=int(math.pow(2,len(rule))),
                p=p
            )
        )

    linC_D = computeLinC_D(dataset,rule)

    #print(linC_D)
    #print(M_inv)

    C_T_11 = vectormatrixProdMod(linC_D,M_inv)

    #print(C_T_11)

    return C_T_11/len(dataset)
    

In [42]:

def MASK_Apriori(dataset: DataFrame, p: float, min_sup,levels: int):
    rules = [
        [],
        [ [item] for item in dataset.columns ]
    ]

    for i in range(1, levels+1):
        print(f"Constructing Level: {i}")
        # remove all the rules in rules[i]
        # that don't have a support of at least min_sup

        #print(f"RULES[{i}] BEFORE", rules[i]
        
        if len(rules[i]) == 0:
            break


        

        if i <levels:
            rules.append([])
            for rule in rules[i]:
                for item in dataset.columns:

                    # skip if item is already inside the rule
                    if item in rule:
                        continue

                    else: rules[i+1].append ( rule + [item] )
                    # create a new rule composed of rule + [item]

    for i in range(1,levels+1):
        print(f"Analysing Level: {i}")
        size = int(math.pow(2,i))
        M_inv = inv(
            computeM(size,p)
        )
        
        rules[i] = [
            rule
            for rule in rules[i]
            if MASK_Support(dataset,rule,p,M_inv) >= min_sup
        ]

    return rules




    

In [44]:
reduced_inventory = inventory[0:10]
print(reduced_inventory)

['almonds', 'antioxydant_juice', 'asparagus', 'avocado', 'babies_food', 'bacon', 'barbecue_sauce', 'black_tea', 'blueberries', 'body_spray']


In [45]:
reduced_test_ds = test_dataset.iloc[0:1000, 0:10]
print(reduced_test_ds)

     almonds  antioxydant_juice  asparagus  avocado  babies_food  bacon  \
0          1                  0          0        1            0      0   
1          0                  0          0        0            0      0   
2          0                  0          0        0            0      0   
3          0                  0          0        1            0      0   
4          0                  0          0        0            0      0   
..       ...                ...        ...      ...          ...    ...   
995        0                  0          0        0            0      0   
996        0                  0          0        0            0      0   
997        0                  0          0        0            0      0   
998        0                  0          0        0            0      0   
999        0                  0          0        0            0      0   

     barbecue_sauce  black_tea  blueberries  body_spray  
0                 0          0           

In [47]:
support_vector_reduced = [[item,support(reduced_test_ds,[item])] for item in reduced_inventory]
print(support_vector_reduced)
mean_reduced_support = np.mean([sublist[1] for sublist in support_vector_reduced])
print(mean_reduced_support)

[['almonds', 0.028], ['antioxydant_juice', 0.0], ['asparagus', 0.006], ['avocado', 0.035], ['babies_food', 0.0], ['bacon', 0.008], ['barbecue_sauce', 0.0], ['black_tea', 0.0], ['blueberries', 0.01], ['body_spray', 0.0]]
0.008700000000000001


In [48]:
p = 0.9
reduced_distorted_test_ds = MASK_Distortion(reduced_test_ds,p)

In [49]:
min_sup = 0.001
levels=3
rules = Apriori(reduced_inventory,reduced_test_ds,min_sup,4)
print(rules)

Apriori Level: 1
Apriori Level: 2
Apriori Level: 3
[[], [['almonds'], ['asparagus'], ['avocado'], ['bacon'], ['blueberries']], [['almonds', 'avocado'], ['avocado', 'almonds'], ['avocado', 'bacon'], ['avocado', 'blueberries'], ['bacon', 'avocado'], ['blueberries', 'avocado']], []]


In [53]:
MASK_rules = MASK_Apriori(reduced_distorted_test_ds,p,min_sup,levels)
print(MASK_rules)

Constructing Level: 1
Constructing Level: 2
Constructing Level: 3
Analysing Level: 1
Analysing Level: 2
Analysing Level: 3
[[], [['almonds'], ['antioxydant_juice'], ['asparagus'], ['avocado'], ['bacon'], ['blueberries']], [['almonds', 'asparagus'], ['almonds', 'avocado'], ['almonds', 'barbecue_sauce'], ['asparagus', 'almonds'], ['asparagus', 'avocado'], ['asparagus', 'barbecue_sauce'], ['asparagus', 'black_tea'], ['asparagus', 'blueberries'], ['asparagus', 'body_spray'], ['avocado', 'almonds'], ['avocado', 'asparagus'], ['avocado', 'babies_food'], ['avocado', 'blueberries'], ['babies_food', 'avocado'], ['babies_food', 'black_tea'], ['babies_food', 'blueberries'], ['bacon', 'barbecue_sauce'], ['barbecue_sauce', 'almonds'], ['barbecue_sauce', 'asparagus'], ['barbecue_sauce', 'bacon'], ['barbecue_sauce', 'blueberries'], ['barbecue_sauce', 'body_spray'], ['black_tea', 'asparagus'], ['black_tea', 'babies_food'], ['black_tea', 'body_spray'], ['blueberries', 'asparagus'], ['blueberries', 'avo

In [51]:
MASK_Support(reduced_distorted_test_ds,['antioxydant_juice', 'asparagus'],p)

0.015625 * 804
-0.140625 * 187
1.265625 * 9


np.float64(-0.00234375)